name: workflow for Codecov

on: [push, pull_request]

jobs:
  run:
    runs-on: ubuntu-latest
    # We want to run on external PRs, but not on our own internal PRs as they'll be run
    # by the push to the branch.
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository
    env:
      PYTHON: '3.8'
      LALPULSAR_DATADIR: ${{ github.workspace }}/ephem
    steps:
    - uses: actions/checkout@master
    - name: Setup Python
      uses: actions/setup-python@master
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Set up ephemerides
      run: |
        export EPHEM_SRC=https://git.ligo.org/lscsoft/lalsuite/raw/master/lalpulsar/lib
        echo "LALPULSAR_DATADIR: $LALPULSAR_DATADIR"
        mkdir $LALPULSAR_DATADIR
        wget $EPHEM_SRC/earth00-40-DE405.dat.gz -P $LALPULSAR_DATADIR
        wget $EPHEM_SRC/sun00-40-DE405.dat.gz -P $LALPULSAR_DATADIR
        echo "Successfully downloaded ephemerides:"
        ls -l $LALPULSAR_DATADIR
    - name: Generate coverage report
      run: |
        pip install pytest
        pip install pytest-cov
        pytest tests.py::TestWriter --cov=./ --cov-report=xml
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        files: ./coverage.xml
        directory: ./coverage/reports/
        flags: unittests
        env_vars: PYTHON
        name: codecov-umbrella
        fail_ci_if_error: true
        path_to_write_report: ./coverage/codecov_report.txt
        verbose: true
