name: Integration Tests

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    # We want to run on external PRs, but not on our own internal PRs as they'll be run
    # by the push to the branch.
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: "3.12"
    - name: Install package and development dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e ${GITHUB_WORKSPACE}[style]
    - name: Linting with flake8
      run: |
        flake8 --count --statistics .
